# Generated by Django 4.0.6 on 2022-09-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('detial', models.CharField(max_length=1000000, null=True)),
                ('points_detail1', models.TextField(blank=True, max_length=300)),
                ('points_detail2', models.TextField(blank=True, max_length=300)),
                ('points_detail3', models.TextField(blank=True, max_length=300)),
                ('points_detail4', models.TextField(blank=True, max_length=300)),
                ('points_detail5', models.TextField(blank=True, max_length=300)),
                ('points_detail6', models.TextField(blank=True, max_length=300)),
                ('points_detail7', models.TextField(blank=True, max_length=300)),
                ('points_detail8', models.TextField(blank=True, max_length=300)),
                ('right_side_paragraph', models.TextField(blank=True, max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='AccountsA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250)),
                ('shortparagraph', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='AccountsB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficer_message', models.TextField(blank=True, max_length=300)),
                ('image', models.ImageField(upload_to='images/')),
                ('name_of_officer', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('facebook', models.URLField(max_length=250)),
                ('phone', models.CharField(max_length=100)),
                ('twitter', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Advertisements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('detail', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('uploaded', models.DateTimeField(auto_now_add=True, null=True)),
                ('pdf_ver', models.FileField(blank=True, upload_to='pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='Count_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('FY', models.CharField(max_length=100)),
                ('total_no', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Development',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('detail', models.CharField(blank=True, max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('uploaded', models.DateTimeField(auto_now_add=True, null=True)),
                ('pdf_file', models.FileField(blank=True, upload_to='pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='Executives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('image', models.FileField(blank=True, upload_to='images/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('top_paragraph', models.TextField(blank=True)),
                ('point1', models.CharField(blank=True, max_length=300)),
                ('point2', models.CharField(blank=True, max_length=300)),
                ('point3', models.CharField(blank=True, max_length=300)),
                ('point4', models.CharField(blank=True, max_length=300)),
                ('point5', models.CharField(blank=True, max_length=300)),
                ('summary', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_q', models.CharField(max_length=300)),
                ('ans_q', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('details', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='GBIRCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250)),
                ('shortparagraph', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='GBIRCB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficer_message', models.TextField(blank=True, max_length=300)),
                ('image', models.ImageField(upload_to='images/')),
                ('name_of_officer', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('facebook', models.URLField(max_length=250)),
                ('phone', models.CharField(max_length=100)),
                ('twitter', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfficersA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250)),
                ('shortparagraph', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='OfficersB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficer_message', models.TextField(blank=True, max_length=300)),
                ('image', models.ImageField(upload_to='images/')),
                ('name_of_officer', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('facebook', models.URLField(blank=True, max_length=250)),
                ('phone', models.CharField(blank=True, max_length=150)),
                ('twitter', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ppdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('uploaded', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('upload_file', models.FileField(blank=True, upload_to='pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='SectionA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250)),
                ('shortparagraph', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SectionB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficer_message', models.TextField(blank=True, max_length=300)),
                ('image', models.ImageField(upload_to='images/')),
                ('name_of_officer', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('facebook', models.URLField(max_length=250)),
                ('phone', models.CharField(max_length=100)),
                ('twitter', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('post_image', models.FileField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Social_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, help_text='facebook link')),
                ('twitter', models.URLField(blank=True, help_text='twitter link')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=100)),
                ('instagram', models.URLField(blank=True, help_text='Intagram link')),
                ('skype', models.URLField(blank=True, help_text='skype number')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
